collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.6009667
color:
  saturation: 0.9683136
  brandStrength: 0.9951664
  lightness: 1
  brandColors:
    - '#121212'
    - '#232323'
    - '#02B8D7'
    - '#FFFFFE'
    - '#1C717F'
  rhythmicContrast: 0.8200859
layout_spectrum: 0.6772288
name: Marc Gasser
